# Generated by Django 5.1.4 on 2024-12-09 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
                ("localisation", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Occupant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=15)),
                ("cni", models.CharField(max_length=20, unique=True)),
                ("nom_complet", models.CharField(max_length=255)),
                ("numero_contrat", models.CharField(max_length=50, unique=True)),
                ("date_debut_contrat", models.DateField()),
                ("loyer", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_prochain_paiement", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("Actif", "Actif"), ("En retard", "En retard")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupant",
                "verbose_name_plural": "Occupants",
            },
        ),
        migrations.CreateModel(
            name="Compartiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CHAMBRE", "Chambre"),
                            ("APPARTEMENT", "Appartement"),
                            ("STUDIO", "Studio"),
                            ("BOUTIQUE", "Boutique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "statut",
                    models.CharField(
                        choices=[("LIBRE", "Libre"), ("OCCUPE", "Occupé")],
                        default="LIBRE",
                        max_length=10,
                    ),
                ),
                ("chambres", models.IntegerField(default=0)),
                ("salons", models.IntegerField(default=0)),
                ("douches", models.IntegerField(default=0)),
                ("cuisines", models.IntegerField(default=0)),
                (
                    "logement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compartiments",
                        to="app.logement",
                    ),
                ),
                (
                    "occupant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.occupant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant_verse", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paiement", models.DateField(default=django.utils.timezone.now)),
                ("date_prochain_paiement", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("Payé", "Payé"), ("En attente", "En attente")],
                        max_length=20,
                    ),
                ),
                (
                    "occupant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="app.occupant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
            },
        ),
    ]
