# Generated by Django 5.1.4 on 2024-12-09 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="occupant",
            options={},
        ),
        migrations.AddField(
            model_name="occupant",
            name="logement",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.logement",
            ),
            preserve_default=False,
        ),
    ]
