# Generated by Django 5.1.4 on 2024-12-10 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_occupant_options_occupant_logement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupant",
            name="logement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.logement",
            ),
        ),
    ]
