# Generated by Django 5.1.4 on 2026-05-17 02:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_occupant_logement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement']},
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='date_prochain_paiement',
            new_name='date_debut_periode',
        ),
        migrations.RemoveField(
            model_name='compartiment',
            name='occupant',
        ),
        migrations.AddField(
            model_name='occupant',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occupant',
            name='compartiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='app.compartiment'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_fin_periode',
            field=models.DateField(default=datetime.date(2026, 6, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='nombre_mois',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paiement',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='logement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='app.logement'),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('En retard', 'En retard'), ('Parti', 'Parti')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('Payé', 'Payé'), ('En attente', 'En attente')], default='Payé', max_length=20),
        ),
    ]
