# Generated by Django 5.1.4 on 2026-05-17 03:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_paiement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='occupant',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='numero_contrat',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='HistoriqueOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_occupant', models.CharField(blank=True, max_length=255)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('loyer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compartiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='app.compartiment')),
                ('occupant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='app.occupant')),
            ],
            options={
                'ordering': ['-date_entree'],
            },
        ),
    ]
