# Generated by Django 5.1.4 on 2026-08-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_logement_date_creation_occupant_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupant',
            name='caution_versee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('OM', 'Orange Money'), ('MOMO', 'MTN MoMo'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20),
        ),
    ]
