# Generated by Django 5.1.4 on 2026-08-01 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_backfill_logement_proprietaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='occupant',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupants_geres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='cni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='numero_contrat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='occupant',
            unique_together={('proprietaire', 'cni'), ('proprietaire', 'email'), ('proprietaire', 'numero_contrat')},
        ),
    ]
