# Generated by Django 5.1.4 on 2026-08-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_backfill_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartiment',
            name='loyer_reference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compartiment',
            name='mezzanine',
            field=models.BooleanField(default=False),
        ),
    ]
