# Generated by Django 5.1.4 on 2026-08-01 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_compartiment_loyer_reference_compartiment_mezzanine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('categorie', models.CharField(choices=[('REPARATION', 'Réparations'), ('ELECTRICITE', 'Électricité'), ('EAU', 'Eau'), ('TAXE', 'Taxe'), ('ENTRETIEN', 'Entretien'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='app.logement')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
