# Generated by Django 5.1.4 on 2026-08-02 01:58

import app.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_depense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compartiment',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='occupant',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CNI_PASSEPORT', 'CNI / Passeport'), ('CONTRAT_SIGNE', 'Contrat signé'), ('FACTURE_TRAVAUX', 'Facture travaux'), ('QUITTANCE_EXTERNE', 'Quittance externe'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('fichier', models.FileField(upload_to=app.models.document_upload_path, validators=[app.models.valider_fichier_document])),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('taille_octets', models.PositiveIntegerField(default=0)),
                ('date_televersement', models.DateTimeField(auto_now_add=True)),
                ('logement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.logement')),
                ('occupant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.occupant')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_televersement'],
            },
        ),
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('date_realisation', models.DateField(default=django.utils.timezone.now)),
                ('etat_general', models.CharField(choices=[('BON', 'Bon'), ('MOYEN', 'Moyen'), ('MAUVAIS', 'Mauvais')], default='BON', max_length=10)),
                ('cles_remises', models.PositiveIntegerField(default=0)),
                ('observations', models.TextField(blank=True)),
                ('champs_details', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compartiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etats_des_lieux', to='app.compartiment')),
                ('logement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etats_des_lieux', to='app.logement')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_des_lieux', to='app.occupant')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_des_lieux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_realisation'],
            },
        ),
    ]
