# Generated by Django 5.1.4 on 2026-08-02 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_compartiment_date_creation_occupant_date_fin_contrat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatdeslieux',
            name='date_realisation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
