# Generated by Django 5.1.4 on 2026-08-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupant',
            name='date_versement_caution',
            field=models.DateField(blank=True, null=True),
        ),
    ]
